// Package curated is the CuratedProvider: a hand-maintained catalog of real
// products whose outbound links are affiliate links generated by us in each
// partner's own panel. There is no marketplace API call: the curated tables
// (managed from the admin panel) are the source of truth, so price and availability are never shown as live data.
// See docs/integrations/curated.md.
package curated

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/listou/listou/apps/api/internal/affiliate"
	"github.com/listou/listou/apps/api/internal/catalog/textnorm"
)

const Adapter = "CURATED"

// Source supplies the active catalog entries (Postgres in production).
type Source interface {
	List(ctx context.Context, onlyActive bool) ([]Product, error)
}

type Provider struct{ src Source }

func New(src Source) *Provider { return &Provider{src: src} }

func (p *Provider) Adapter() string { return Adapter }

func (p *Provider) SearchProducts(ctx context.Context, q affiliate.SearchQuery) ([]affiliate.ProductData, error) {
	entries, err := p.src.List(ctx, true)
	if err != nil {
		return nil, err
	}
	terms := textnorm.Tokens(q.Text)
	type scored struct {
		e     Product
		score int
	}
	var hits []scored
	for _, e := range entries {
		hay := textnorm.Normalize(e.Title + " " + e.Brand + " " + e.Keywords + " " + e.Category)
		score := 0
		for _, t := range terms {
			if strings.Contains(hay, t) {
				score++
			}
		}
		if len(terms) == 0 || score > 0 {
			hits = append(hits, scored{e, score})
		}
	}
	sort.SliceStable(hits, func(i, j int) bool { return hits[i].score > hits[j].score })
	limit := q.Limit
	if limit <= 0 || limit > 50 {
		limit = 20
	}
	out := make([]affiliate.ProductData, 0, min(limit, len(hits)))
	for i := 0; i < len(hits) && i < limit; i++ {
		out = append(out, product(hits[i].e))
	}
	return out, nil
}

// GetProduct also serves disabled entries: items already on a list keep working.
func (p *Provider) GetProduct(ctx context.Context, externalID string) (affiliate.ProductData, error) {
	entries, err := p.src.List(ctx, false)
	if err != nil {
		return affiliate.ProductData{}, err
	}
	for _, e := range entries {
		if e.ExternalID == externalID {
			return product(e), nil
		}
	}
	return affiliate.ProductData{}, affiliate.ErrNotFound
}

func (p *Provider) GetOffers(ctx context.Context, externalID string) ([]affiliate.OfferData, error) {
	pd, err := p.GetProduct(ctx, externalID)
	if err != nil {
		return nil, err
	}
	return pd.Offers, nil
}

// BuildAffiliateURL returns the curated link exactly as registered; nothing is
// appended or rewritten.
func (p *Provider) BuildAffiliateURL(_ context.Context, _, productURL string, _ affiliate.ClickContext) (string, error) {
	if !isHTTP(productURL) {
		return "", fmt.Errorf("curated: invalid product url")
	}
	return productURL, nil
}

func product(e Product) affiliate.ProductData {
	pd := affiliate.ProductData{ExternalID: e.ExternalID, Title: e.Title}
	if e.Brand != "" {
		pd.Brand = &e.Brand
	}
	if e.Category != "" {
		pd.Category = &e.Category
	}
	if e.Emoji != "" {
		pd.Emoji = &e.Emoji
	}
	if e.ImageURL != "" {
		pd.ImageURL = &e.ImageURL
	}
	for _, o := range e.Offers {
		pd.Offers = append(pd.Offers, affiliate.OfferData{
			MerchantCode: o.Merchant,
			ExternalID:   e.ExternalID + "-" + o.Merchant,
			Title:        e.Title,
			Currency:     "BRL",
			Availability: affiliate.Unknown,
			ProductURL:   o.URL,
			ImageURL:     pd.ImageURL,
		})
	}
	return pd
}
